version: '3'

services:

  mysql_master:

    image: mysql

    env_file:

      - ./Master/master.env

    container_name: "mysql_master"

    ports:

      - 4406:3306

    volumes:

      - ./Master/Config/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf

      - ./Master/data:/var/lib/mysql

  mysql_slave:

    image: mysql

    env_file:

      - ./Slave/slave.env

    container_name: "mysql_slave"
     
    ports:

      - 5506:3306

    depends_on:

      - mysql_master

    volumes:

      - ./Slave/Config/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf

      - ./Slave/data:/var/lib/mysql

  CheckMySql:

    image: sql_checker

    build:

      context: .

      dockerfile: .\Dockerfile

    ports:

      - 3000:3000

    volumes:

          - ./db-data:/var/lib/mysql
          - ./output:/output

    depends_on:

      - mysql_master

      - mysql_slave
  jenkins:
    image: "jenkins/jenkins:lts"
    privileged: true
    user: "root"
    ports:
      - "0000:0000"
      - "5000:5000"
    dns:
      - 8.8.8.8
    volumes:
      - "./jenkins:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/resolv.conf:/etc/resolv.conf"
      - "/usr/bin/docker:/usr/bin/docker"